### PR TITLE
Merged Noto fonts

### PR DESCRIPTION
**Pull request by rinigus**
I have merged Noto fonts using my scripts. Please note that I haven't had a chance to test them since I don't have tilelive server running anywhere. It works in OSM Scout Server via database, but should work via files as well.

The ranges are generated only if there were glyphs in that range. This is an approach that is expected to become a default, if I remember from Mapbox issues correctly. You can symlink missing ranges from fonts that you wish to be used as a substitute. For example, Noto Italic has rather few glyphs available.

Fixes https://github.com/otsaloma/cartago-styles/issues/2

### CODE REVIEW

**Comment by otsaloma** [comment]
Seems to work fine. It looks a bit different, e.g. Thai has simpler forms, Arabic is bigger and bolder. Did you use the latest Noto release for your conversion? If so, that would likely explain it – the Klokantech conversion is from a year ago.

I'll do the rest – edit the style JSON and remove the Klokantech versions.

**Comment by rinigus** [comment]
Yes, its the latest fonts that I downloaded few days ago for OSM Scout Server. Great to hear that it works. If we can transfer styles to these, it will be easier to convert styles between Cartago and OSM Scout Server.

**Comment by otsaloma** [comment]
Thanks, merging.

**Comment by otsaloma** [comment]
Updated on server as well.

**Comment by rinigus** [comment]
Great!

**Pull request merged**
